export enum Status {
  ACTIVE = 'ACTIVE',
  PENDING = 'PENDING',
  EXPIRED = 'EXPIRED',
  INACTIVE = 'INACTIVE',
  CANCELED = 'CANCELED',
  CONFIRMED = 'CONFIRMED',
  PROCESSING = 'PROCESSING',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  RETURNED = 'RETURNED',
}
export enum accessType {
  OTP = 'OTP',
  GOOGLE = 'GOOGLE',
}
